version: '2'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: passpass
      WORDPRESS_DB_NAME: TP2_Environnement_de_travail_collaboratif
    volumes:
      - ./wp-content:/var/www/html/wp-content/
    depends_on:
      - db

  db:
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      MYSQL_DATABASE: TP2_Environnement_de_travail_collaboratif
      MYSQL_USER: user
      MYSQL_PASSWORD: passpass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    depends_on:
      - db
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - ./appapp/:/usr/share/nginx/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - "./log:/var/log/nginx"
    depends_on:
      - php-fpm
      - db
  php-fpm:
    image: php:7.2-fpm
    container_name: php
    restart: always
    volumes:
      - ./app/:/usr/share/nginx/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

